networks:
  apiLaravel:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-api
    restart: unless-stopped
    tty: true
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ApiLaravel:/var/www/app:delegated
    depends_on:
      - php
    networks:
      - apiLaravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-api
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - ./ApiLaravel:/var/www/app:delegated
    networks:
      - apiLaravel
    depends_on:
      - mssql
      # - selenium

  mssql:
    container_name: mssql-api
    hostname: mssql-api
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Passw0rd'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    networks:
      - apiLaravel
    ports: 
      - "1433:1433"
    volumes:
      - ./DB/data:/var/opt/mssql/data
      - ./DB/log:/var/opt/mssql/log
      - ./DB/secrets:/var/opt/mssql/secrets

  # selenium:
  #   image: selenium/standalone-chrome
  #   container_name: selenium
  #   hostname: selenium
  #   ports:
  #     - "4444:4444"
  #     - "7900:7900"
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   networks:
  #     - siteBNL